version: "2.1"

volumes:
  data:
  walletstore:

networks:
  trade:

services:
  explorerdb.abacsupplychain.io:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.abacsupplychain.io
    hostname: explorerdb.abacsupplychain.io
    environment:
      - DATABASE_DATABASE=$EXPLORER_DB_NAME
      - DATABASE_USERNAME=$EXPLORER_DB_USERNAME
      - DATABASE_PASSWORD=$EXPLORER_DB_PASSWORD
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - trade

  explorer.abacsupplychain.io:
    image: hyperledger/explorer:latest
    container_name: explorer.abacsupplychain.io
    hostname: explorer.abacsupplychain.io
    environment:
      - DATABASE_HOST=explorerdb.abacsupplychain.io
      - DATABASE_DATABASE=$EXPLORER_DB_NAME
      - DATABASE_USERNAME=$EXPLORER_DB_USERNAME
      - DATABASE_PASSWD=$EXPLORER_DB_PASSWORD
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer/connection-profile.json:/opt/explorer/app/platform/fabric/connection-profile.json
      - ./explorer/walletstore:/opt/wallet
      - ./crypto-config:/etc/hyperledger/fabric/crypto
    command: sh -c "node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8080:8080
    depends_on:
      explorerdb.abacsupplychain.io:
        condition: service_healthy
    networks:
      - trade
