version: "2"

volumes:
  orderer.abacsupplychain.io:
  peer0.retailer.abacsupplychain.io:
  peer0.producer.abacsupplychain.io:
  peer0.shipper.abacsupplychain.io:
  peer0.regulator.abacsupplychain.io:

networks:
  trade:
services:
  retailer-ca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.retailer.abacsupplychain.io
      - FABRIC_CA_CERT_FILE=/etc/hyperledger/fabric-ca-server-config/ca.retailer.abacsupplychain.io-cert.pem
      - FABRIC_CA_KEY_FILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.retailer.abacsupplychain.io-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/retailer.abacsupplychain.io/ca:/etc/hyperledger/fabric-ca-server-config
      - ./crypto-config/peerOrganizations/retailer.abacsupplychain.io/tlsca:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.retailer.abacsupplychain.io
    networks:
      - trade

  producer-ca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.producer.abacsupplychain.io
      - FABRIC_CA_CERT_FILE=/etc/hyperledger/fabric-ca-server-config/ca.producer.abacsupplychain.io-cert.pem
      - FABRIC_CA_KEY_FILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.producer.abacsupplychain.io-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/producer.abacsupplychain.io/ca:/etc/hyperledger/fabric-ca-server-config
      - ./crypto-config/peerOrganizations/producer.abacsupplychain.io/tlsca:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.producer.abacsupplychain.io
    networks:
      - trade

  shipper-ca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.shipper.abacsupplychain.io
      - FABRIC_CA_CERT_FILE=/etc/hyperledger/fabric-ca-server-config/ca.shipper.abacsupplychain.io-cert.pem
      - FABRIC_CA_KEY_FILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.shipper.abacsupplychain.io-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/shipper.abacsupplychain.io/ca:/etc/hyperledger/fabric-ca-server-config
      - ./crypto-config/peerOrganizations/shipper.abacsupplychain.io/tlsca:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.shipper.abacsupplychain.io
    networks:
      - trade

  regulator-ca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.regulator.abacsupplychain.io
      - FABRIC_CA_CERT_FILE=/etc/hyperledger/fabric-ca-server-config/ca.regulator.abacsupplychain.io-cert.pem
      - FABRIC_CA_KEY_FILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.regulator.abacsupplychain.io-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/regulator.abacsupplychain.io/ca:/etc/hyperledger/fabric-ca-server-config
      - ./crypto-config/peerOrganizations/regulator.abacsupplychain.io/tlsca:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.regulator.abacsupplychain.io
    networks:
      - trade

  orderer.abacsupplychain.io:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.abacsupplychain.io
    container_name: orderer.abacsupplychain.io
    networks:
      - trade

  peer0.producer.abacsupplychain.io:
    container_name: peer0.producer.abacsupplychain.io
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.producer.abacsupplychain.io
    networks:
      - trade

  peer0.retailer.abacsupplychain.io:
    container_name: peer0.retailer.abacsupplychain.io
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.retailer.abacsupplychain.io
    networks:
      - trade

  peer0.shipper.abacsupplychain.io:
    container_name: peer0.shipper.abacsupplychain.io
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.shipper.abacsupplychain.io
    networks:
      - trade

  peer0.regulator.abacsupplychain.io:
    container_name: peer0.regulator.abacsupplychain.io
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.regulator.abacsupplychain.io
    networks:
      - trade
