version: "2"

services:
  orderer.abacsupplychain.io:
    container_name: orderer.abacsupplychain.io
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/abacsupplychain.io/orderers/orderer.abacsupplychain.io/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/abacsupplychain.io/orderers/orderer.abacsupplychain.io/tls/:/var/hyperledger/orderer/tls
      - orderer.abacsupplychain.io:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.retailer.abacsupplychain.io:
    container_name: peer0.retailer.abacsupplychain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.retailer.abacsupplychain.io
      - CORE_PEER_ADDRESS=peer0.retailer.abacsupplychain.io:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.retailer.abacsupplychain.io:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.retailer.abacsupplychain.io:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.retailer.abacsupplychain.io:7051
      - CORE_PEER_LOCALMSPID=RetailerMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/retailer.abacsupplychain.io/peers/peer0.retailer.abacsupplychain.io/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/retailer.abacsupplychain.io/peers/peer0.retailer.abacsupplychain.io/tls:/etc/hyperledger/fabric/tls
      - peer0.retailer.abacsupplychain.io:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.producer.abacsupplychain.io:
    container_name: peer0.producer.abacsupplychain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.producer.abacsupplychain.io
      - CORE_PEER_ADDRESS=peer0.producer.abacsupplychain.io:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.producer.abacsupplychain.io:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.abacsupplychain.io:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.abacsupplychain.io:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/producer.abacsupplychain.io/peers/peer0.producer.abacsupplychain.io/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/producer.abacsupplychain.io/peers/peer0.producer.abacsupplychain.io/tls:/etc/hyperledger/fabric/tls
      - peer0.producer.abacsupplychain.io:/var/hyperledger/production
    ports:
      - 8051:7051

  peer0.shipper.abacsupplychain.io:
    container_name: peer0.shipper.abacsupplychain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.shipper.abacsupplychain.io
      - CORE_PEER_ADDRESS=peer0.shipper.abacsupplychain.io:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.shipper.abacsupplychain.io:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.shipper.abacsupplychain.io:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shipper.abacsupplychain.io:7051
      - CORE_PEER_LOCALMSPID=ShipperMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/shipper.abacsupplychain.io/peers/peer0.shipper.abacsupplychain.io/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/shipper.abacsupplychain.io/peers/peer0.shipper.abacsupplychain.io/tls:/etc/hyperledger/fabric/tls
      - peer0.shipper.abacsupplychain.io:/var/hyperledger/production
    ports:
      - 9051:7051

  peer0.regulator.abacsupplychain.io:
    container_name: peer0.regulator.abacsupplychain.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.regulator.abacsupplychain.io
      - CORE_PEER_ADDRESS=peer0.regulator.abacsupplychain.io:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.regulator.abacsupplychain.io:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regulator.abacsupplychain.io:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regulator.abacsupplychain.io:7051
      - CORE_PEER_LOCALMSPID=RegulatorMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/regulator.abacsupplychain.io/peers/peer0.regulator.abacsupplychain.io/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/regulator.abacsupplychain.io/peers/peer0.regulator.abacsupplychain.io/tls:/etc/hyperledger/fabric/tls
      - peer0.regulator.abacsupplychain.io:/var/hyperledger/production
    ports:
      - 10051:7051
