# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check client application
      run: |
        cd application/client
        npm i
        npm run lint
        npm run build

    - name: Check server application
      run: |
        cd application/server
        npm i
        npm run lint
